apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-rzzuxnub
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-rzzuxnub:7cc5837f0d12c608868d6774e5b868427ce7ee6b@sha256:20ed5c1a9c63f4a9c3057a4f9fa1b907d4f579144b0441e31adb1e30a305f14f
          name: container-image
